### PR TITLE
Format task lists in README

### PR DESCRIPTION
**Pull request by byronsharman**

### CODE REVIEW

**Comment by byronsharman** [comment]
oh bummer the latest commit creates conflicts with merging this

**Comment by byronsharman** [comment]
I just reset it to master and then re-did the changes, so there should not be any conflicts now.

**Review by joshlangley — COMMENTED** [review]
Oops. I guess I should touch up on my markdown. I have made changes to README since this request, but I will fix this issue. Thanks!

**Comment by byronsharman** [comment]
Looks solid now, so I will close this merge request. Good work :+1:

**Pull request closed without merging**
